### PR TITLE
Problem: copy command at line leaves environment variables out

### PR DESCRIPTION
**Pull request by FrancescElies**
When I copy a command with `prodigy-copy-cmd`  I would like to get the environmet variables copied to the kill-ring to be able to paste the command directly in a terminal.

This PR adds environment variables to the yank command. Would this make sense to you?

### CODE REVIEW

**Comment by Fuco1** [comment]
I have an idea.  The implementation now assumes the user is using bash/zsh or something like that. If we use `env` binary (which is I think available everywhere) we can support fish and other non-posix shells too.

It should work like so:

    env foo=bar foo2=bar2 binary -arg ....

**Comment by FrancescElies** [comment]
I didn't think about those cases at all, the idea sounds good to me,
I'll implement it next week.

**Comment by FrancescElies** [comment]
@Fuco1 `env` binary added to yank command

Minor thing, I see in travis `stub-service --stub-arg` & `env STUB_ENV_A=a STUB_ENV_B=b stub-service --stub-arg` being printed, I believe it's because of the `message` command inside `prodigy-copy-cmd`. Shall I do something about it, (see [travis-job](https://travis-ci.org/rejeep/prodigy.el/jobs/346179309))?

**Comment by Fuco1** [comment]
I don't think that's a big deal if it prints stuff out, but if we absolutely want to keep it quiet there's [shut-up](https://github.com/cask/shut-up) package for exactly that

**Comment by FrancescElies** [comment]
> I don't think that's a big deal if it prints stuff out, but if we absolutely want to keep it quiet there's shut-up package for exactly that

Added shut-up to cask dependencies and updated test, no more prints now

**Comment by Fuco1** [comment]
LGTM :+1:

**Comment by FrancescElies** [comment]
How do you feel about this one 🙏 ? ☺️

**Pull request merged**
