### PR TITLE
Properly stop process started with sudo

### LINKED ISSUE #111: sudo issues
I just tried out the new `:sudo` parameter and ran into a few bugs:

1. since the process is spawned with sudo the usual `(signal-process ...)` won't be able to kill it without also gaining elevated permissions

1. for commands that are in the sudoers file with `NOPASSWD`, prodigy will still prompt for a password and accidentally send that password to the spawned process as input

~~It seems to me that setting `:cwd "/sudo::/"` is enough? That will use tramp and not interfere with (2) and will also correctly kill the process which solves (1). Thoughts?~~ I incorrectly tested `:cwd`, so  I don't have a solution yet :-(

### PR DESCRIPTION
**Pull request by isamert**
Prodigy can't stop processes started with sudo because it does not
have the privileges to do that. This PR simply fixes that by running
the `kill` command with `prodigy-start-sudo-process` and with given
`stop-signal`. Partially fixes #111.

### CODE REVIEW

**Comment by Fuco1** [comment]
Maybe a different approach would be to set default directory using TRAMP and sudo protocol and then call the original code.  I would as much as possible try to use the `stop-process` and similar Emacs commands instead of using utilities such as `pgrep` which aren't necessarily very portable.

**Comment by isamert** [comment]
While writing a response I figured out a way to not depending on `pgrep`, turns out sending the signal with appending `-` before the process group id redirects the signal to all children, which greatly simplified the implementation.

I agree that utilizing TRAMP would be the best possible solution but there are a few blockers:

- Current `:sudo t` depends on calling `sudo` itself directly, so we need a whole refactor here to make it work with TRAMP.
- Signalling the process directly does not work, because `sudo` creates a process group and sending a signal to this group is not passed to the children (I don't know why though, this is something about how `sudo` works). We still need to figure out what the child process id's are and signal them or we will use `kill` with the `-` trick again (but at least kill is more portable?).

Currently killing services with `:sudo t` does not work at all, this PR at least fixes that. With the latest change, it's even simpler.

**Comment by Fuco1** [comment]
Apparently this repo requires all commits to be signed:

image

Is this an option for you?  If not, I can rebase them somehow so they get signed (it should still retain you as the author though, I don't want to take the credit)

**Comment by isamert** [comment]
Sorry for getting back late, thanks for the heads up. Signed the commits and updated.

**Comment by isamert** [comment]
@Fuco1 just a nudge to remind you about this.

**Comment by DamienCassou** [comment]
@isamert Could you please squash your 2 commits into 1? I can do it if you prefer.

**Comment by isamert** [comment]
You can squash if it's okay for you, thanks!

**Comment by DamienCassou** [comment]
Done. Thank you very much for your work.

**Pull request merged**
