### PR TITLE
Add prodigy-copy-url

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by Fuco1** [comment]
I'm trying to re-run the failed tests, but it seems the travis setup is kind of getting broken for a lot of projects.

Recently there's been the addition of github action by @purcell so I think we could migrate to that.  We put it in the dash project and it works very well and is a lot faster than travis as well.

**Comment by Fuco1** [comment]
I'm going to optimistically merge it.  Tests pass on older versions and from the review I don't see any issues.

**Comment by DamienCassou** [comment]
> I'm trying to re-run the failed tests, but it seems the travis setup is kind of getting broken for a lot of projects.

I'm not sure Travis is to blame in this case, I would try to fix Cask first. I have stopped using Cask and made [makel](https://gitea.petton.fr/DamienCassou/makel) because I couldn't trust Cask anymore. Since then, I never had any similar problem. Here is an example project that uses Travis+Nix+makel: https://github.com/DamienCassou/beginend

**Comment by Fuco1** [comment]
I think it's the combination of cask and evm which makes it flaky.  But yea cask has its share of problems.

**Pull request merged**
